FROM arey/mysql-client

COPY tables.sql /tmp/
WORKDIR /tmp
RUN ls
WORKDIR /
COPY ./script.sh /usr/local/bin/docker-entrypoint.sh

RUN ln -s usr/local/bin/docker-entrypoint.sh /


ENTRYPOINT ["docker-entrypoint.sh"]



