---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
 name: csye7374-v2-notifier
spec:
 maxReplicas: 15
 minReplicas: 1
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: csye7374-assign3-rc-notifier
 metrics:
 - type: Resource
   resource:
     name: cpu
     targetAverageUtilization: 1