apiVersion: v1
kind: Service
metadata:
  name: csye7374-lb-svc-notifier
spec:
  type: LoadBalancer            
  ports:
  - name: http
    protocol: TCP
    port: 80                 
    targetPort: 5001
  - name: https
    protocol: TCP
    port: 443
    targetPort: 5001          
  selector:
    app: csye7374-notifier